name: Markdown to PDF

on:
  push:
    branches:
      - main # or your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find all Markdown files
        id: find_markdown
        run: |
          mkdir output  # create output dir
          echo "files=$(find . -type f -name "*.md" -not -path "./output/*" -not -path "*/\.*" | sort | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Setup Pandoc
        uses: docker://pandoc/extra:latest

      - name: Convert Markdown files to PDF
        run: |
            for file in ${{ steps.find_markdown.outputs.files }}; do
            filename=$(basename "$file" .md)
            echo "Converting $file to output/$filename.pdf"
            docker run --rm -v ${{ github.workspace }}:/data pandoc/extra:latest "$file" -o "output/$filename.pdf" --template eisvogel --listings
            done

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: release-${{ steps.date.outputs.date }}
            release_name: Release ${{ steps.date.outputs.date }}
            draft: false
            prerelease: false

      - name: Upload PDF Files to Release
        run: |
            for pdf in output/*.pdf; do
            filename=$(basename "$pdf")
            gh release upload release-${{ steps.date.outputs.date }} "$pdf" --clobber
            done
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}